use My_test
CREATE TABLE ORDERS
( ORDNA INT NOT NULL UNIQUE,
  MONTH INT,
  CID INT,
  AID INT,
  PID INT,
  QTY INT,
  DOLLARS INT,
  PNAME CHAR(20),
  PRIMARY KEY(ORDNA),
  FOREIGN KEY(CID) REFERENCES CUSTOMERS ON DELETE CASCADE,
  FOREIGN KEY(PID) REFERENCES PRODUCTS ON DELETE CASCADE,
  FOREIGN KEY(AID) REFERENCES AGENTS ON DELETE CASCADE
)